### ISSUE TITLE
Fix typo in README.md

### ISSUE THREAD

**Issue by jordanhailey** [sensu/sensu-enterprise-workshop#4]
Under step 1, in the side note about using jq to check the json files just created, fix the line that reads

`$ cat /etc/sensu/conf.d/influxdb.json | jq .`

to 

`$ cat /etc/sensu/conf.d/handlers/influxdb.json | jq .`

**Comment by calebhailey** [comment]
Oh, good catch! Thanks, @jordanhailey! :+1:
