### ISSUE TITLE
Lesson 7, Exercise 2 linux install instructions are invalid

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-enterprise-workshop#41]
## Feedback

The instructions for installing a Linux agent are incorrect (they expect some environment variables that we don't set in .envrc). The `tar` command also needs to be executed via `sudo`. 

## Suggested Improvement

```
curl -LO https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/${SENSU_VERSION}/sensu-go_${SENSU_VERSION}_linux_amd64.tar.gz
sudo tar -xzf sensu-go_${SENSU_VERSION}_linux_amd64.tar.gz -C /usr/bin/  
rm sensu-go_${SENSU_VERSION}_linux_amd64.tar.gz    
```

## Lesson Progress

- [ ] Lesson 01 completed or in-progress
- [ ] Lesson 02 completed or in-progress
- [ ] Lesson 03 completed or in-progress
- [ ] Lesson 04 completed or in-progress
- [ ] Lesson 05 completed or in-progress
- [ ] Lesson 06 completed or in-progress
- [x] Lesson 07 completed or in-progress
- [ ] Lesson 08 completed or in-progress
- [ ] Lesson 09 completed or in-progress
- [ ] Lesson 10 completed or in-progress
- [ ] Lesson 11 completed or in-progress
- [ ] Lesson 12 completed or in-progress
- [ ] Lesson 13 completed or in-progress
- [ ] Lesson 14 completed or in-progress
- [ ] Lesson 15 completed or in-progress
- [ ] Lesson 16 completed or in-progress

**Comment by thoward** [comment]
Note: this should have been closed by #42, but wasn't. Closing now.
