### ISSUE TITLE
Can't access chat UI

### ISSUE THREAD

**Issue by hackartisan** [sensu/sensu-enterprise-workshop#96]
## Feedback

There appears to be an in-progress migration from rocket chat to mattermost. The links still go to port 5000 in the documentation, although the chat service port has changed. If you do find the port and navigate to http://127.0.0.1:8065 the given login information does not work. It seems like maybe the logic to add the user to rocket chat was deleted but logic to add the user to mattermost was not added.

This means lessons 5 and 6, and likely lessons following, can't be completed because the effects of the exercises can't be observed.

## Suggested Improvement

What branch or commit can I run the tutorial from in a known-working state?

## Lesson Progress

- [x] Lesson 01 completed or in-progress
- [x] Lesson 02 completed or in-progress
- [x] Lesson 03 completed or in-progress
- [x] Lesson 04 completed or in-progress
- [x] Lesson 05 completed or in-progress
- [x] Lesson 06 completed or in-progress
- [ ] Lesson 07 completed or in-progress
- [ ] Lesson 08 completed or in-progress
- [ ] Lesson 09 completed or in-progress
- [ ] Lesson 10 completed or in-progress
- [ ] Lesson 11 completed or in-progress
- [ ] Lesson 12 completed or in-progress
- [ ] Lesson 13 completed or in-progress
- [ ] Lesson 14 completed or in-progress
- [ ] Lesson 15 completed or in-progress
- [ ] Lesson 16 completed or in-progress

**Comment by thoward** [comment]
Thanks so much! I just checked, and it looks like this was fixed. Please reopen if you run into this again.

**Comment by calebhailey** [comment]
@hackartisan thanks for this issue! Please feel free to register your contribution for free swag!! 

https://sensu.io/register-your-contribution :tada:
