### ISSUE TITLE
sensu-agent not starting up using docker on linux

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-enterprise-workshop#99]
## Suggested Improvement
the sensu-agent container definition is trying to use
the default `ws://localhost:8081`  for backend url 

But this causes the sensu-agent container to fail to start up.

I need to add `--backend-url "ws://sensu-backend:8081"`  to the `sensu-agent start` invocation defined in the docker-compose file to have it working again.

**Comment by jspaleta** [comment]
tracked this down to how sudo operates.

When `sudo docker-compose`  MAY depending on how sudo is configured strip the env vars.
`docker-compose`  sans sudo   will prefer the env vars.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go-workshop/blob/latest/TROUBLESHOOTING.md#deploying-the-workshop-using-docker-compose-without-sudo
